# how to determine the number of peaks to look for
mass_cutoffs:
  # initial cutoff is at zero
  - [0, 3]
  - [1500, 4]
  - [2400, 5]
  # addition cutoffs follow
  # - [2400, 5]

# given in minutes
rt_proximity_tolerance: !!int 1

# given in parts per million
mz_proximity_tolerance: !!int 100

# required_unique: !!int 0

start_time: !!float 0.0

study_type: "tissue"

aa_elemental_composition_path: "aa_elem_compositions.tsv"

aa_labeling_sites_path: "aa_labeling_sites.tsv"
  
elements_path: "elements.tsv"
  
post_translational_modifications_path: "ptms.json"

# ppm_cutoff: 2

# score_cutoff: 0

# rt_min_distance: 3

#Determine the min and max charge state to search for
min_charge_state: !!int 1
max_charge_state: !!int 1

# Decide if duplicate molecules in the ID file precursor should be removed.
remove_duplicates: !!bool True

# Select which adducts should be used in the PCDL Converter:
# Positive Mode Adducts:
H_adduct: !!bool True
Na_adduct: !!bool True
H_H2O_adduct: !!bool True
Na_H2O_adduct: !!bool True
NH4_adduct: !!bool True
NH4_H2O_adduct: !!bool True

# Negative Mode Adducts:
formate_adduct: !!bool False
acetate_adduct: !!bool False
e_adduct: !!bool False
H_loss: !!bool False
H2O_loss: !!bool False
