ID_weight: 0.7
aa_labeling_sites_path: /home/JCPriceLab/Desktop/Paper DeuteRater Versions/DeuteRater
  Final/resources/aa_labeling_sites.tsv
abundance_agreement_filter: 0.1
abundance_manual_bias: 0.0
adduct_weight: 1.0
allowed_neutromer_peak_variance: 10
allowed_peak_variance_min: 0.2
asymptote: Fixed
baseline_lookback: 100
bias_calculation: None
chunk_size: 600
chunking_method_threshold: 2
combined_agreement_filter: 0.1
combined_manual_bias: 0.0
debug_level: 1
enrichement_of_zero: 0.05
error_of_non_replicated_point: 0.05
error_of_zero: 0.01
fixed_asymptote_value: 1.0
fpe_tolerance: 0.0078125
heavy_isotope: H
how_divided: combined
id_file_rt_unit: min
intensity_filter: 20000
intensity_weight: 0.6
labeling_step_size: 0.001
lipid_analyte_id_column: Lipid Unique Identifier
lipid_analyte_name_column: Lipid Name
max_valid_angle: 1.2
maximum_theoretical_pct: 0.071
min_aa_sequence_length: 6
min_allowed_abund_max_delta: 0.04
min_allowed_n_values: 10
min_envelopes_to_combine: 10
minimum_abund_change: 0.04
minimum_nonzero_points: 3
ms_level: 1
mz_proximity_tolerance: 0.0
n_processors: 8
peak_lookahead: 1
peak_lookback: 1
peak_ratio_denominator: 10
peptide_analyte_id_column: Protein_ID
peptide_analyte_name_column: Protein_Name
ppm_window: 30
proliferation_adjustment: 0.0
rate_output_format: png
recognize_available_cores: false
rel_height: 0.9
roll_up_rate_calc: true
sampling_rate: 3
smoothing_order: 3
smoothing_width: 9
spacing_agreement_filter: 0.1
spacing_manual_bias: 0.0
study_type: tissue_test
time_window: 1.5
trim_ids_to_mzml_bounds: false
unique_sequence_column: Sequence
use_abundance: Average
use_chromatography_division: Intrafile
use_empir_n_value: false
use_neutromer_spacing: false
variance_weight: 1.0
verbose_rate: false
y_intercept_of_fit: 0.0
zscore_cutoff: 1.0
