ID_weight: 0.7
aa_labeling_sites_path: C:\Users\admin\Desktop\DeuteRater-dev\resources\aa_labeling_sites.tsv
abundance_agreement_filter: 0.1
abundance_manual_bias: 0.0
abundance_type: M0
adduct_weight: 1.0
allowed_neutromer_peak_variance: 64
allowed_peak_variance_min: 0.1
asymptote: Fixed
baseline_lookback: 100
bias_calculation: none
chunk_size: 50
chunking_method_threshold: 2
combined_agreement_filter: 0.1
combined_manual_bias: 0.0
debug_level: 0
error_of_non_replicated_point: 0.05
error_of_zero: 0.01
fixed_asymptote_value: 1.0
fraction_new_calculation: combined
graph_n_value_calculations: false
graph_output_format: png
how_divided: combined
id_file_rt_unit: sec
intensity_filter: 20000
intensity_weight: 0.6
label_key: tissue
lipid_analyte_id_column: Lipid Unique Identifier
lipid_analyte_name_column: Lipid Name
max_fn_standard_deviation: 0.1
max_valid_angle: 1.2
maximum_allowed_sequence_rate: 1.5
min_aa_sequence_length: 6
min_allowed_n_values: 2
min_envelopes_to_combine: 10
minimum_allowed_sequence_rate: 0.0
minimum_nonzero_points: 3
ms_level: 1
mz_proximity_tolerance: 100
n_processors: 2
n_value_cv_limit: 0.1
peak_lookahead: 1
peak_lookback: 1
peak_ratio_denominator: 10
peptide_analyte_id_column: Protein_ID
peptide_analyte_name_column: Protein_Name
ppm_window: 30
proliferation_adjustment: 0.0
r2_threshold: 0.5
recognize_available_cores: true
rel_height: 0.9
remove_filters: false
rt_proximity_tolerance: 1.0
s_n_filter: 0.0
sampling_rate: 9
save_n_value_data: false
separate_adducts: false
smoothing_order: 3
smoothing_width: 49
spacing_agreement_filter: 0.1
spacing_manual_bias: 0.0
time_window: 1.5
trim_ids_to_mzml_bounds: false
unique_sequence_column: Sequence
use_chromatography_division: 'No'
use_empir_n_value: false
use_outlier_removal: false
variance_weight: 1.0
verbose_rate: true
y_intercept_of_fit: 0.0
zscore_cutoff: 1.0
